# GitHub repository settings managed via Probot Settings
repository:
  name: tmux-config
  description: Personal tmux configuration
  homepage: https://github.com/idvoretskyi/tmux-config
  topics: [tmux, config, dotfiles]
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
branches:
  - name: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - CI / Tmux Lint
          - Security / Gitleaks
          - Security / Scorecards
      enforce_admins: true
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      restrictions: null
